### Load in NumPy (remember to pip install numpy first)

In [62]:
import numpy as np

### The Basics

In [63]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [64]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [65]:
# Get Dimension
a.ndim

1

In [66]:
# Get Shape
b.shape

(2, 3)

In [67]:
# Get Type
b.dtype

dtype('float64')

In [68]:
# Get Size
a.itemsize

4

In [69]:
# Get total size
a.nbytes

12

In [70]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [71]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [72]:
# Get a specific element [r, c]
a[1, -1]

14

In [73]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [74]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [77]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [80]:
a[1,5] = 20
print(a)

a[:,2] = [5, 10]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


*3-d example

In [81]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [84]:
# Get specific element (work outside in)
b[1,-2,-1]

6

In [85]:
# replace 
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### Initializing Different Types of Arrays

In [86]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [87]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [88]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [89]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [90]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.0144126 , 0.75374475],
       [0.32525025, 0.59552248],
       [0.06403757, 0.61067804],
       [0.29442052, 0.25047163]])

In [91]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-4, -4,  5],
       [-3,  4, -4],
       [ 7,  4,  7]])

In [92]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [94]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [95]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

### Mathematics

In [ ]:
a = np.array([1,2,3,4])
print(a)

In [ ]:
a + 2

In [ ]:
a - 2

In [ ]:
a * 2

In [ ]:
a / 2

In [ ]:
b = np.array([1,0,1,0])
a + b

In [ ]:
a ** 2

In [ ]:
# Take the sin
np.cos(a)



In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

In [ ]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

In [ ]:
np.min(stats)

In [ ]:
np.max(stats, axis=0) # axis=0 column wise operation across rows

In [ ]:
np.max(stats, axis=1) # axis=1 row wise operation across columns

In [ ]:
np.sum(stats, axis=0)

In [ ]:
np.sum(stats, axis=1)

### Reorganizing Arrays

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

In [ ]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

In [ ]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(h1)
print(h2)

np.hstack((h1,h2))

### Miscellaneous
##### Load Data from File

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

##### Boolean Masking and Advanced Indexing

In [ ]:
filedata > 50

In [ ]:
filedata[filedata > 50]

In [ ]:
#### Indexing numpy with a list
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a[[0, 1, 3]]

In [ ]:
np.any(filedata > 50, axis = 0)

In [ ]:
(~((filedata > 50) & (filedata < 100)))