### Load in NumPy (remember to pip install numpy first)

In [60]:
import numpy as np
import pandas as pd

C:\Users\Dipen\Anaconda3\lib\site-packages\pandas\compat\_optional.py:138: UserWarning: Pandas requires version '2.7.0' or newer of 'numexpr' (version '2.6.9' currently installed).
  warnings.warn(msg, UserWarning)


### The Basics

In [3]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dimension
a.ndim

1

In [6]:
# Get Shape
b.shape

(2, 3)

In [7]:
# Get Type
b.dtype

dtype('float64')

In [8]:
# Get Size
a.itemsize

4

In [9]:
# Get total size
a.nbytes

12

In [10]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [11]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
# Get a specific element [r, c]
a[1, -1]

14

In [13]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [15]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [16]:
a[1,5] = 20
print(a)

a[:,2] = [5, 10]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


*3-d example

In [17]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
# Get specific element (work outside in)
b[1,-2,-1]

6

In [19]:
# replace 
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### Initializing Different Types of Arrays

In [20]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [22]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [23]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [24]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.36307889, 0.98037207],
       [0.31725334, 0.20020584],
       [0.57142762, 0.02909151],
       [0.28202899, 0.49782666]])

In [25]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 1,  2,  3],
       [ 2,  7, -1],
       [ 3,  0,  6]])

In [26]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [28]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [29]:
a = np.array([1,2,3])
b = a.copy()
#b = a
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


### Mathematics

In [30]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [31]:
a + 2

array([3, 4, 5, 6])

In [32]:
print(a)

[1 2 3 4]


In [33]:
a - 2

array([-1,  0,  1,  2])

In [34]:
a * 2

array([2, 4, 6, 8])

In [35]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [36]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [37]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [38]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [39]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [40]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [41]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [42]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [43]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
np.min(stats)

1

In [45]:
np.max(stats, axis=0) # axis=0 column wise operation across rows

array([4, 5, 6])

In [46]:
np.max(stats, axis=1) # axis=1 row wise operation across columns

array([3, 6])

In [47]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [48]:
np.sum(stats, axis=1)

array([ 6, 15])

### Reorganizing Arrays

In [49]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [50]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [51]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(h1)
print(h2)

np.hstack((h1,h2,h1))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 0., 1., 1., 1., 1.]])

### Miscellaneous
##### Load Data from File

In [85]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [86]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [87]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [55]:
#### Indexing numpy with a list
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a[[0, 1, 3]]

array([1, 2, 4])

In [88]:
np.any(filedata > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [89]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [58]:
x = np.array([[[0], [1], [2]]])
x.shape

(1, 3, 1)

In [59]:
np.squeeze(x).shape

(3,)

In [61]:
### importing a dataset
dataset = pd.read_csv('weight-height.csv')

In [65]:
dataset.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [90]:
np_dataset = dataset.to_numpy()

In [67]:
np_dataset[0,:]

array(['Male', 73.847017017515, 241.893563180437], dtype=object)

In [72]:
bmi = np_dataset[:,2]/(np_dataset[:,1] ** 2)

In [73]:
print(bmi)

[0.04435661514692517 0.034308217461467276 0.03873432923942884 ...
 0.03149583862678362 0.03438142193500951 0.02961856891403506]


In [74]:
array_class = np.array([[1, 2 ,3 ,4 ,5], [6, 7 ,8 ,9 ,10], [11, 12 ,13 ,14 ,15], [16, 17 ,18 ,19 ,20], [21, 22 ,23 ,24 ,25], [26, 27 ,28 ,29 ,30]])

In [75]:
print(array_class)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [79]:
array_class[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [80]:
array_class[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [83]:
array_class[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])